[build]
  functions = "netlify/functions"

# Ensure function paths are never rewritten by SPA routes
[[redirects]]
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true

# Your SPA/static fallback (keep if you need it)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
