[build]
  functions = "netlify/functions"

# Ensure function paths are not rewritten to index.html
[[redirects]]
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true

# Keep your SPA fallback if you use one
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
